version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS_ENV=localhost,127.0.0.1,test1.sensix.com.br
      - DEBUG=True

  app2:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS_ENV=localhost,127.0.0.1,test2.sensix.com.br
      - DEBUG=True

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  static_data: